### ISSUE TITLE
Improve region lifecycle setup in the config

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#126]
Probably keep separate life cycles for the basic functions to keep it a bit more clear?

**Example `config.yml` layout:**

``` yaml
lifecycles:
  events: # Events, executed each time the region switches to the mentioned state.
    addedEvent:
      # Everything before `-` determines the actions, after is a label?
      # Allows multiple of the same types
      saveSchematic: '%type%-%region%'
    deletedEvent:
      restoreSchematic: '%type%-%region%'
    rentedEvent:
      saveSchematicIfNone: '%type%-%region%' # Only save when not already saved
    extendedEvent:
    unrentedEvent:
      restoreSchematic: '%type%-%region%'
    boughtEvent:
    soldEvent:
      restoreSchematic: '%type%-%region%'
    resellingEvent:
    resoldEvent:
    updateEvent: # all updates this is triggered
    # Possible events based on Bukkit events
    newOwnerEvent:
    addedFriendEvent:
    removedFriendEvent:


  states: # Actions depending on the region state, applied each time it updates
    allState: # Better name for this?
      flags:
        priority: 10
        members: ''
        interact: 'deny g:non_members'
        build: 'deny g:non_members'
        block-break: 'deny g:non_members'
        block-place: 'deny g:non_members'
    forrentState:
      flags:
        greeting: '%lang:prefix%%lang:greeting-forrent%'
      sign:
        line1: '&2&l[For Rent]'
        line2: '%region%'
        line3: '%duration%'
        line4: '%price%'
        rightClickPlayer:
        - 'areashop rent %region%'
        leftClickPlayer:
        - 'areashop info region %region%'
    rentedState:
      flags:
        members: '%uuid%, %friendsuuid%'
        greeting: '%lang:prefix%%lang:greeting-rented%'
      sign:
        line1: '&4&l[Rented]'
        line2: '%region%'
        line3: '%player%'
        line4: '%untilshort%'
        rightClickPlayer:
        - 'areashop rent %region%'
        leftClickPlayer:
        - 'areashop info region %region%'
        shiftRightClickPlayer:
        - 'areashop message %clicker% %lang:confirm-unrent|%region%|%'
    forsaleState:
      flags:
        greeting: '%lang:prefix%%lang:greeting-forsale%'
      sign:
        line1: '&2&l[For Sale]'
        line2: '%region%'
        line3: '%price%'
        line4:
        rightClickPlayer:
        - 'areashop buy %region%'
        leftClickPlayer:
        - 'areashop info region %region%'
    soldState:
      flags:
        members: '%uuid%, %friendsuuid%'
        greeting: '%lang:prefix%%lang:greeting-bought%'
      sign:
        line1: '&4&l[Sold]'
        line2: '%region%'
        line3: '%player%'
        line4:
        rightClickPlayer:
        - 'areashop buy %region%'
        leftClickPlayer:
        - 'areashop info region %region%'
        shiftRightClickPlayer:
        - 'areashop message %clicker% %lang:confirm-sell|%region%|%'
    resellingState:
      flags:
        members: '%uuid%, %friendsuuid%'
        greeting: '%lang:prefix%%lang:greeting-resale%'
      sign:
        line1: '&9&l[Resale]'
        line2: '%region%'
        line3: '%resellprice%'
        line4: '&8%player%'
        rightClickPlayer:
        - 'areashop buy %region%'
        leftClickPlayer:
        - 'areashop info region %region%'
        shiftRightClickPlayer:
        - 'areashop stopresell %region%'
```

**Example `default.yml` setting**

``` yaml
# The lifecycles to apply, applied from top to bottom
lifecycles:
- states
- events
```

_Inspired by Androkai_
