### ISSUE TITLE
Error at Startup, after switching to PermissionsEx

### ISSUE THREAD

**Issue by BadBlackLion** [NLthijs48/AreaShop#142]
Hey,
I'm actually trying to "handcraft" a server on my own a bit. While doing so I changed my permissions to PermissionsEx and after a restart I got this [error](http://pastebin.com/K7jvNjQJ). I know it must be something simple I can't see at the moment...
[Here](http://pastebin.com/741Crht9) you can find my config.yml and [this](http://pastebin.com/a0yJdvXE) is my default.yml.

I'm looking forward to hear from you.

Yours Sincerely
Sebastian

**Comment by EvilOlaf** [comment]
Search for
```
expirationWarningProfiles:
  default:
    '1 Tag':
      warnPlayer: true
      commands:
    - "say Mietvertrag für %region% von Spieler %player% läuft in %timeleft% aus."
    '1 Stunde':
      warnPlayer: false
      commands:
    '5 Minuten':
      warnPlayer: false
      commands:
```
replace with
```
expirationWarningProfiles:
  default:
    '1 Tag':
      warnPlayer: true
      commands:
      - "say Mietvertrag für %region% von Spieler %player% läuft in %timeleft% aus."
    '1 Stunde':
      warnPlayer: false
      commands:
    '5 Minuten':
      warnPlayer: false
      commands:
```

Should do the trick.
