### ISSUE TITLE
Hello i want to ask if you have a comand or a setting in config.yml so when some1 rent a house the flags of worldguard change(so whit that we can stop griefing)

### ISSUE THREAD

**Issue by TulioXD** [NLthijs48/AreaShop#169]
Helperino plz

**Comment by NLthijs48** [comment]
Check the `flagProfiles` section in the `config.yml` file, there you can setup which flags should be set on the WorldGuard region. By default the flags should already prevent griefing, you might have another WorldGuard region overriding certain flags though.

**Comment by TulioXD** [comment]
how can i put like something to make when someone buy the place only can use chest and doors and not build or delete something
btw i have here my flag profile idk how to put flags in there

flagProfiles:
  default:
    forrent:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
    forsale:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'

**Comment by NLthijs48** [comment]
Using the flags below should do the trick. You can use all flags that you can also set with the `/region flag <region> <flag> [value...]` command of WorldGuard.
```yaml
flagProfiles:
  default:
    forrent:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
      interact: 'deny g:non_members'
      use: 'deny g:non_members'
      build: 'deny'
    forsale:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
      interact: 'deny g:non_members'
      use: 'deny g:non_members'
      build: 'deny'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
      interact: 'deny g:non_members'
      use: 'deny g:non_members'
      build: 'deny'
```
