### ISSUE TITLE
Use hover and click in chat messages

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#18]
Using hover and click events on chat messages could greatly improve the usage of commands, and the feedback of commands. For example '/as me' could show [info] and [tp] buttons for your regions to immediately do those actions. This could make using AreaShop easier for the player.

Example:
![](http://dev.bukkit.org/media/images/75/825/Hover_text.png)

Current work in progress version can be found at [github.com/NLthijs48/FancyMessageFormat](https://github.com/NLthijs48/FancyMessageFormat), this is a collaboration with PhoenixIV from the RegionForSale plugin.

**Comment by NLthijs48** [comment]
Getting somewhere with this, basic implementation done. Message can be defined in the config file with hover and click things, then AreaShop replaces variables, inserts other messages into them and sends them to the player.

Left to do:

- [ ] Support for giving variables to language inserts: `%lang:command|/as help%` should insert the message with the key `command` with as replacement for `%0%` using `/as help`. This makes writing messages that look alike easier, for example the messages of the help list. Also keeps the formatting of such thing in 1 place.
- [ ] Script to export the EN.yml file to a format that Transifex can correctly read. Single YAML strings with embedded `\n` and `\t` looks like the best option. (basic script already exists, support for multiline messages required)
- [ ] Script to import all language files from Transifex and get them ready for use. (script already exists, support for multiline messages required, inverse of export script).
- [ ] Adding a lot more hover/click things all over the place.
- [ ] Add explanation about the new messages on the wiki for the translators.

**Comment by NLthijs48** [comment]
Variable inserts done, to give an example, this is what I use for the help messages. 

```yaml
command:
  - "&6%0% &7-&r"
  - "  hover: &9&l<use %0%>"
  - "  command: %0%"

help-info: "%lang:command|/as info% Get info about current regions."
```

So if AreaShop prints the `help-info` message, this message will get the `command` part inserted, with an argument `/as info`. The argument is used in the `command` message with `%0%` to set the text, set the hover text, and set the command to execute on click. Very powerful if you ask me :)

**Comment by NLthijs48** [comment]
Added a lot of clickable things again, mostly clicking region names and player names: https://github.com/NLthijs48/AreaShop/commit/38b658fccf0cf395b541ba8520b8b0f2d8a33fd9

Updated task list above.

**Comment by NLthijs48** [comment]
Script for getting the EN.yml file ready for Transifex is done, below is a picture of how it looks in Transifex. This should work fine for translating these kind of messages.

![screenshot_1](https://cloud.githubusercontent.com/assets/6951068/15802158/30d1e3f8-2aaa-11e6-920b-7fd802e1e1fb.png)

**Comment by NLthijs48** [comment]
The messages have been uploaded to Transifex, so the translating can begin :)

**Comment by NLthijs48** [comment]
All implemented, closing the ticket.

Of course adding more hover/click things where they make sense is an ongoing task, so that will happen later.

**Comment by Andr416h** [comment]
I got a problem in my server the Areashop says:
![2016-10-17_12 31 09](https://cloud.githubusercontent.com/assets/22885483/19434432/a059c130-9465-11e6-8fa9-3e380db70fd7.png)

**Comment by NLthijs48** [comment]
@Andr416h This is an error in the config of the current release version of AreaShop, update your `signProfiles` section of the `config.yml` file to [this one](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L93-L153). If you have already modified it, you could also change `shiftRightClickPlayer` to `shiftRightClickConsole` for the section where you use `/as message` (and `rightClickPlayer` to `rightClickConsole`)

Let me know if that solves your problem.

**Comment by Andr416h** [comment]
Now it says this:
![rip](https://cloud.githubusercontent.com/assets/22885483/19434793/c230539e-9467-11e6-86a4-fb9b1b3dab96.png)
And i have only changed the lang.

**Comment by Andr416h** [comment]
Are you there?

**Comment by Andr416h** [comment]
Ive actually don't want the hover to be there i went it away can you send a config where it isnt there.

**Comment by NLthijs48** [comment]
@Andr416h 

> Are you there?

This is not an instant chat.

Use this config if you don't want confirmations:
```yaml
signProfiles:
  default:
    forrent:
      line1: '&2&l[For Rent]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickPlayer:
      - 'areashop rent %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
    rented:
      line1: '&4&l[Rented]'
      line2: '%region%'
      line3: '%player%'
      line4: '%untilshort%'
      rightClickPlayer:
      - 'areashop rent %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop unrent %region%'
    forsale:
      line1: '&2&l[For Sale]'
      line2: '%region%'
      line3: '%price%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
    resell:
      line1: '&9&l[Resale]'
      line2: '%region%'
      line3: '%resellprice%'
      line4: '&8%player%'
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop stopresell %region%'
    sold:
      line1: '&4&l[Sold]'
      line2: '%region%'
      line3: '%player%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop sell %region%'
```
