### ISSUE TITLE
Restore Regions after unrent

### ISSUE THREAD

**Issue by nifeboy123** [NLthijs48/AreaShop#197]
http://pastebin.com/A2QtgvVW <--- Config YML
http://pastebin.com/EE3yxxbi <---- Default YML
http://pastebin.com/VcAnhkJn <---- Group YML
Basically I want the D regions to reset and have it not affect other regions I plan to setup. The schematic name that's in the schematic folder is called dcell.schematic

**Comment by NLthijs48** [comment]
First I advise you to read [this wiki page](https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore), that will give you some information about how the restore system works. What you can do is first creating an extra schematic profile, then assigning that profile to the dcells group.

**config.yml file**
```yaml
schematicProfiles:
  default:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: ''
      restore: ''
    unrented:
      save: ''
      restore: '%type%-dcell'
    bought:
      save: ''
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
    resell:
      save: ''
      restore: ''
  restorecell:
    unrented:
      save: ''
      restore: 'dcell' # .schematic is added automatically
    sold:
      save: ''
      restore: 'dcell'
```

**groups.yml file**
```yaml
dcells:
  name: dcells
  priority: 0
  general:
    schematicProfile: 'restorecell'
    enableRestore: true
  regions:
  - D-Cell1
  - D-Cell10
```

Now all regions in the dcells group should restore from the defined schematic file. Note that currently you do have restoring enable for all regions, so they will also reset. You can change this by setting `enableRestore` in the `default.yml` file to `false`, and then setting `enableRestore` in the group file to `true` (like I already added above).

Let me know if you need any more help.
