### ISSUE TITLE
Default signProfile tries to execute `/as message` as player instead of console

### ISSUE THREAD

**Issue by nyco007** [NLthijs48/AreaShop#221]
Hi,

I've got the problem, that users can't use AreShop. AreaShop gives the message: "You do not have oermission to send AreaShop messages."
What can I do?

**Comment by evernife** [comment]
Aadd permission

>  ***- areashop.message***

I spend a lot time to discover too :V

Need to put this in the wiki, and add as a default perm too!

**Comment by NLthijs48** [comment]
The fix of @evernife is a workaround, not a real solution to the actual problem. The `/as message` command should never be used by players, it is meant to be executed by the console. In order to actually fix the problem the config file has to change. The `signProfles` section should change to the following:

```yaml
signProfiles:
  default:
    forrent:
      line1: '&2&l[For Rent]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickPlayer:
      - 'areashop rent %region%'
      rightClickConsole:
      #- 'areashop message %clicker% %lang:confirm-rent|%region%|%' # Alternative to first ask for confirmation
      leftClickPlayer:
      - 'areashop info region %region%'
    rented:
      line1: '&4&l[Rented]'
      line2: '%region%'
      line3: '%player%'
      line4: '%untilshort%'
      rightClickPlayer:
      - 'areashop rent %region%'
      rightClickConsole:
      #- 'areashop message %clicker% %lang:confirm-extend|%region%|%' # Alternative to first ask for confirmation
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickConsole:
      - 'areashop message %clicker% %lang:confirm-unrent|%region%|%'
    forsale:
      line1: '&2&l[For Sale]'
      line2: '%region%'
      line3: '%price%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      rightClickConsole:
      #- 'areashop message %clicker% %lang:confirm-buy|%region%|%' # Alternative to first ask for confirmation
      leftClickPlayer:
      - 'areashop info region %region%'
    resell:
      line1: '&9&l[Resale]'
      line2: '%region%'
      line3: '%resellprice%'
      line4: '&8%player%'
      rightClickPlayer:
      - 'areashop buy %region%'
      rightClickConsole:
      #- 'areashop message %clicker% %lang:confirm-buy|%region%|%' # Alternative to first ask for confirmation
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop stopresell %region%'
    sold:
      line1: '&4&l[Sold]'
      line2: '%region%'
      line3: '%player%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickConsole:
      - 'areashop message %clicker% %lang:confirm-sell|%region%|%'
```

For the next version of AreaShop I will change this, for now you can copy this section to your own config file. The change I made is swapping `rightClickPlayer` for `rightClickConsole`, which executes the commands from the console instead of by the player itself.
