### ISSUE TITLE
Flag Profiles not working

### ISSUE THREAD

**Issue by c0wg0d** [NLthijs48/AreaShop#225]
Hello,

My shops are not having the region flags updated properly in WorldGuard on rent/unrent events.  Can you help me figure out why?

flagProfiles section in config.yml

```
flagProfiles:
  mallshops:
    forrent:
      owners: ''
      members: ''
      build: 'deny'
      chest-access: 'deny'
      use: 'deny'
      greeting: ''
    rented:
      owners: ''
      members: '%uuid%, %friendsuuid%'
      build: 'deny'
      chest-access: 'allow g:members'
      use: 'allow'
      greeting: ''
    forsale:
      members: ''
      greeting: ''
    sold:
      members: ''
      greeting: ''
    resale:
      members: ''
      greeting: ''
  buildshops:
    forrent:
      owners: ''
      members: ''
      build: 'deny'
      chest-access: 'deny'
      use: 'deny'
      greeting: ''
    rented:
      owners: ''
      members: '%uuid%, %friendsuuid%'
      build: 'allow g:members'
      chest-access: 'allow g:members'
      use: 'allow'
      greeting: ''
    forsale:
      members: ''
      greeting: ''
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: ''
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: ''
```

groups.yml
```
mallshops:
  name: mallshops
  priority: 0
  regions:
  - atlantismall01
  - atlantismall02
  - atlantismall03
  - atlantismall04
  - atlantismall05
  - atlantismall06
  - atlantismall07
  - atlantismall08
  - atlantismall09
  - atlantismall10
  - atlantismall11
  - atlantismall13
  - atlantismall21
  - atlantismall22
  - atlantismall23
  - atlantismall14
  - atlantismall15
  - atlantismall16
  - atlantismall17
  - atlantismall18
  - atlantismall19
  - atlantismall20
  - atlantismall24
  - atlantismall25
  - atlantismall26
  - atlantismall12
buildshops:
  name: buildshops
  priority: 0
  regions:
  - atlantisbuildsmall01
  - atlantisbuildsmall02
  - atlantisbuildsmall05
  - atlantisbuildsmall04
  - atlantisbuildsmall03
  - atlantisbuildsmall06
  - atlantisbuildsmall07
  - atlantisbuildsmall08
  - atlantisbuildsmall09
  - atlantisbuildsmall10
  - atlantisbuildsmall11
  - atlantisbuildsmall12
  - atlantisbuildsmall13
  - atlantisbuildsmall14
  - atlantisbuildsmall15
  - atlantisbuildsmall16
  - atlantisbuildsmall17
  - atlantisbuildsmall18
  - atlantisbuildsmall19
  - atlantisbuildsmall20
  - atlantisbuildlarge01
  - atlantisbuildlarge02
  - atlantisbuildlarge03
  - atlantisbuildlarge04
  - atlantisbuildlarge05
  - atlantisbuildlarge06
  - atlantisbuildlarge07
  - atlantisbuildlarge08
  - atlantisbuildlarge09
  - atlantisbuildlarge10
  - atlantisbuildlarge11
  - atlantisbuildlarge12
  - atlantisbuildlarge13
  - atlantisbuildlarge14
  - atlantisbuildlarge15
  - atlantisbuildlarge16
  - atlantisbuildlarge17
  - atlantisbuildlarge18
  - atlantisbuildlarge19
  - atlantisbuildlarge20
```

I tried renting and unrenting atlantismall12 and it doesn't update any flags or remove me as a member on the region (it did add me as a member somehow).

I am using Spigot 1.10.2, WorldGuard v6.1.2;e38d98d, and AreaShop v2.3.2#CUSTOM.

**Comment by NLthijs48** [comment]
Making the name of a flagProfile the same as a region group does not link them together, you need to set the flagProfile in the region group to the correct one. Example:

```yaml
mallshops:
  name: mallshops
  priority: 0
  general:
    flagProfile: mallshops
  regions:
  - atlantismall01
  - atlantismall02
  - atlantismall03
  - atlantismall04
  - atlantismall05
  - atlantismall06
  - atlantismall07
  - atlantismall08
  - atlantismall09
  - atlantismall10
  - atlantismall11
  - atlantismall13
  - atlantismall21
  - atlantismall22
  - atlantismall23
  - atlantismall14
  - atlantismall15
  - atlantismall16
  - atlantismall17
  - atlantismall18
  - atlantismall19
  - atlantismall20
  - atlantismall24
  - atlantismall25
  - atlantismall26
  - atlantismall12
buildshops:
  name: buildshops
  priority: 0
  general:
    flagProfile: buildshops
  regions:
  - atlantisbuildsmall01
  - atlantisbuildsmall02
  - atlantisbuildsmall05
  - atlantisbuildsmall04
  - atlantisbuildsmall03
  - atlantisbuildsmall06
  - atlantisbuildsmall07
  - atlantisbuildsmall08
  - atlantisbuildsmall09
  - atlantisbuildsmall10
  - atlantisbuildsmall11
  - atlantisbuildsmall12
  - atlantisbuildsmall13
  - atlantisbuildsmall14
  - atlantisbuildsmall15
  - atlantisbuildsmall16
  - atlantisbuildsmall17
  - atlantisbuildsmall18
  - atlantisbuildsmall19
  - atlantisbuildsmall20
  - atlantisbuildlarge01
  - atlantisbuildlarge02
  - atlantisbuildlarge03
  - atlantisbuildlarge04
  - atlantisbuildlarge05
  - atlantisbuildlarge06
  - atlantisbuildlarge07
  - atlantisbuildlarge08
  - atlantisbuildlarge09
  - atlantisbuildlarge10
  - atlantisbuildlarge11
  - atlantisbuildlarge12
  - atlantisbuildlarge13
  - atlantisbuildlarge14
  - atlantisbuildlarge15
  - atlantisbuildlarge16
  - atlantisbuildlarge17
  - atlantisbuildlarge18
  - atlantisbuildlarge19
  - atlantisbuildlarge20
```

**Comment by c0wg0d** [comment]
A crucial detail I missed.  Thank you!  Could you possibly add this to the FAQ Page on the wiki?

Suggested content:

Q: Why aren't my region flags being updated properly when a shop is rented, unrented, sold, etc.?

A: If you are using custom flagProfiles, you need to specify them in your groups.yml file.  Example:

```
mallshops:
  name: mallshops
  priority: 0
  general:
    flagProfile: mallshops
  regions:
  - mall01
  - mall02
```
