### ISSUE TITLE
New features proposition.

### ISSUE THREAD

**Issue by emperor321** [NLthijs48/AreaShop#264]
I will very appreciate (and donate for sure) if you add "tax" system, I mean every custom amount of time (e.g every 24hrs) all region owners will automatically pay to the global bank (where a chosen group (using PEX or similar) can have an access to it's bank to take money). That would be group like a "tax collector". I will strongly appreciate it and pay! Because now there are some plugins like this, but you are active dev not like others and you can still do it even better than other.
Or you can make a chest-bank where all collected money will be in that (chosen) chest, so the group (tax collector" won't be needed, because they will have an access to the region with a chest.
I'm making a role-play survival server about Ancient Rome, that's why I'm thinking about it and a "republic bank" in the historical place - temple of Saturn. 

Please tell me if it is even possible

Second good idea is to make a default price for 1m2 (server own region price) and I don't know if you did a possibility to rent for a max. amount of time? I mean if someone will rent a region for a half year and is inactive ... e.g. rent for a maximum 7 days would be great.
Choose a tax price for 1m2 would be great, too ...

I hope you at least answer good sir!

**Comment by NLthijs48** [comment]
**Tax:**
It looks like rental regions is what you should be using. With them the players have to pay for the time they have the region. By setting the `landlord` in the `default.yml` file you can transfer all the money that is collected to an account of your choice (this is a player name, but does not need to exist, so using `taxCollector` should work).

If want the initial cost of the region to be higher than the rent (which you call tax in your case), then you can do this using the `eventCommandProfile` in `default.yml`. You simply set the rental price to the amount players should pay to get the region and then setup commands like this (assuming initial price is 50, 'tax' is 10):

```yaml
  eventCommandProfile:
    created:
      before:
      after:
    #  - "say An AreaShop region has been created: %region%"
    deleted:
      before:
      after:
    rented:
      before:
      after:
      - "areashop setprice 10 %region%"
    extended:
      before:
      after:
    unrented:
      before:
      after:
      - "areashop setprice 50 %region%"
    bought:
      before:
      after:
    sold:
      before:
      after:
    resell:
      before:
      after:
```

By customizing the messages you could also indicate to the user that that the initial price is high and that there is a tax after that. Let me know if that solves your tax situation.

**Price depending on region size:**
Currently a price depending on the region size is not possible, there is a low priority feature request for it though: #23. If you put a like on the issue or comment there then I can keep track of the popularity of the feature.

**Maximum rental time:**
Check the following settings in `default.yml`:
- `maxRentTime`: how far a region can be rented in advance.
- `inactiveTimeUntilUrent`: if and when a region should be unrented because of inactivity.


If you have any more questions let me know :)
