### ISSUE TITLE
Player sends a payment to the landowner

### ISSUE THREAD

**Issue by mark13i** [NLthijs48/AreaShop#278]
I have a question.

The player hires many plots of different owners.
Player sends a payment to the landowner / not to the server.

default.yml
It does not work :(

```
  # The UUID of the landlord, this player will receive all money from rents/buys (but not reselling with '/as resell').
  landlord: '%landlorduuid%' # <---------
  # Name of the landlord, if the landlord UUID setting is not provided then the name will be used instead
  landlordName: '%landlord%' # <---------
```

It also does not work :(

```
 ##### Run commands when an event happens.
  # Commands at a 'before' section will execute before the region details are changed in the AreaShop system
  # and before any other actions occurred (setting the owner, saving/loading schematics, etc.),
  # the 'after' commands will be run when all changes are done.
  # You can add a list of commands to 'before' and 'after'.
  eventCommandProfile:
    rented:
      before:
      - eco give %landlord% %rawprice% # <---------
      after:
    extended:
      before:
      - eco give %landlord% %rawprice% # <---------
      after:
```

How to do it correctly?
