### ISSUE TITLE
groups.yml get wiped out every time after server restarted

### ISSUE THREAD

**Issue by k-jiang** [NLthijs48/AreaShop#299]
#### Current behavior
`groups.yml` get wiped out every single time after server restarted. Even though I could load the groups.yml by `/as reload` command normally.

#### Steps to reproduce (for bugs)

1. put your groups.yml into you plugin folder
2. `/as reload` and it works
3. restart your server
4. `groups.yml` is wiped out, file size becomes zero, gg, have to manually repeat step 1 to make it works again

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2 build 1210
* AreaShop version: 2.4.0
* WorldEdit version: 6.15
* WorldGuard version: 6.2
* Vault version: 1.5.6

#### Your config files (for bugs)

`groups.yml`:
```
xinshoucun-shop:
  name: xinshoucun-shop
  priority: 100
  rent:
    price: 300
    maxRentTime: '30 days'
  general:
    signProfile:
      forrent:
        line1: '&2&l[商店出租]'
        line2: '编号: %region%'
        line3: '%duration%'
        line4: '%price%'
      rented:
        line1: '&4&l[已出租]'
        line2: '编号: %region%'
        line3: '商户: %player%'
        line4: '到期: %untilshort%'
      forsale:
        line1: '&2&l[商店出售]'
        line2: '编号: %region%'
        line3: ''
        line4: '%price%'
      resell:
        line1: '&9&l[商店转让]'
        line2: '编号: %region%'
        line3: '卖家: %resellprice%'
        line4: '&8%player%'
      sold:
        line1: '&4&l[已出售]'
        line2: '编号: %region%'
        line3: '商户: %player%'
        line4: ''
    schematicProfile:
      created:
        save: ''
        restore: ''
      deleted:
        save: ''
        restore: ''
      rented:
        save: ''
        restore: ''
      unrented:
        save: ''
        restore: 'rent-xinshoucun-shop-xx'
      bought:
        save: ''
        restore: ''
      sold:
        save: ''
        restore: ''
      resell:
        save: ''
        restore: ''
    enableRestore: true
  regions:
  - pri-shop-01
  - pri-shop-02
  - pri-shop-03
  - pri-shop-04
  - pri-shop-05
  - pri-shop-06
  - pri-shop-07
  - pri-shop-08
  - pri-shop-09
  - pri-shop-10
  - pri-shop-11
  - pri-shop-12
  - pri-shop-13
```
