### ISSUE TITLE
players permission group and region flags

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#300]
Guys i need some support from ure)

i have players city's with /as
i have pex groups

i need to:

only players from one pex group have activate one flag of AS region.

i using WorldGuardExtraFlags - what have flag /fly

so i want give to all players with only one group of permissions using this flag (without commands - that flag must be in region by default)

but i dont know how change config currectly =( tried other ways but allways have some troubles.

in description thats sound like:

VIP players can fly in there regions.

i will pretty glad if ure help me :-)

**Comment by BabelSolea** [comment]
your plugin easy hook extra flags and they working if i use it in more simple situations, but i need release that case: VIP players can fly in that regions :D

**Comment by NLthijs48** [comment]
It is possible to create regions that[ only VIP players can buy](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples), in which you can then set the flag you need, but that is not exactly what you want.

With an external plugin you can easily make what you need, AreaShop has events you can listen to for detecting renting/unrenting, which in that case can check if the user is VIP and add/remove the flag. I'm not sure if you can create a plugin yourself or have someone to do it though.

There is also another kinda weird option:
- Give VIPs the permission to set the flag you want to set by using the '/region flag <region> <flag>' command (not entirely sure how that works with WorldGuardExtraFlags, but this is possible using the standard WorldGuard flags)
- To the `commandProfile` section in the `default.yml` file add some commands:
```yaml
  eventCommandProfile:
    created:
      before:
      after:
    deleted:
      before:
      after:
    rented:
      before:
      after:
      - "sudo %player% region %region% flag theCustomFlag allow" # Add the flag as the player (will only succeed if the player has permission)
    extended:
      before:
      after:
    unrented:
      before:
      after:
      - "region %region% flag theCustomFlag" # Removes the flag as console
    bought:
      before:
      after:
    sold:
      before:
      after:
    resell:
      before:
      after:
```

This assumes you have Essentials installed for the `sudo` command. The commands will force the player that rented the region to execute a command that adds the flag you want. If the player has permission (which the VIP group should have) it will succeed and add the flag, if he does not the flag will not get added. The only slightly ugly thing is that the player receives a message as confirmation for the command (like 'flag set' or 'permission denied'), but that should not be too bad. 

Let me know if you can work with one of these options, or if you have other ideas yourself.
