### ISSUE TITLE
Commands for owner

### ISSUE THREAD

**Issue by SeussCZ** [NLthijs48/AreaShop#326]
Is possible to add custom command for owner only? For example: When im owner some shop, i can use command "/sell" in specific shop only. When im not a owner, I cant use this command. Thanks

**Comment by EvilOlaf** [comment]
You can define aliases for commands in your `commands.yml` of Spigot.

**Comment by SeussCZ** [comment]
and how i can disable commands /as for all players (default) ?

**Comment by NLthijs48** [comment]
Why would you want that? You know `/as sell` only works for you own regions for normal players? If you have OP you can sell everything though. I'm not sure what you are trying to achieve.

**Comment by SeussCZ** [comment]
I want disable this command for default players.

**Comment by NLthijs48** [comment]
Why?

You can just give your default rank the `-areashop.sellown` permission, this will remove the `/as sell` command for them (it won't show up anymore in `/as`).

**Comment by SeussCZ** [comment]
ok, thanks. And when I want to add new command (fly, tpa, tp) only for shop owner?

**Comment by NLthijs48** [comment]
None of those commands seem to make sense to only allow for the shop owner right? You could of course when someone buys a shop add a permissions to them, and remove it when they lose the shop, then you can allow them any command while they have a shop. Is that what you need?

**Comment by SeussCZ** [comment]
Yes. 
When im shop owner, I can use command /tpa. 
When im not shop owner, I cant use command /tpa

**Comment by NLthijs48** [comment]
Use the 'eventCommandProfiles' section to add/remove permissions:
```yaml
  eventCommandProfile:
    bought:
      before:
      after:
      - "pex user %player% add essentials.tpa"
    sold:
      before:
      - "pex user %player% remove essentials.tpa"
      after:
```
Put that in `default.yml`
