### ISSUE TITLE
Regions depending on rank

### ISSUE THREAD

**Issue by Ornithorink** [NLthijs48/AreaShop#338]
Hello !

I'd like to allow players on my server to buy specific regions depending on their rank.
I have currently two "type" of regions on my server, stand and house. I want stands to be buyable by default but houses to be buyable to players of a specific rank.
I've been through the guide to setup limitsgroup but I didn't manage to do what I want.

Thanks for you help

**Comment by NLthijs48** [comment]
Could you show your config files with what you tried with the limitGroups?

The setup you need would be something like this:
**Limit groups**
```yaml
limitGroups:
  default: # Restrict nothing
    total: -1
    rents: -1
    buys: -1
  noHouse:
    total: 0
    rents: 0
    buys: 0
    group:
    - houses
  house:
    total: -1
    rents: -1
    buys: -1 
    group:
    - houses 
```

**Region group:**
`houses` should contain all house type regions, add them with `/as groupadd houses [region]` (can do it in bulk by making a WorldEdit selection and leaving out the region).

**Permissions:**
Give everyone `areashop.limits.noHouse`, give the specific rank the permission `areashop.limits.house`
