### ISSUE TITLE
cant get shops to work

### ISSUE THREAD

**Issue by DarkSpyro412** [NLthijs48/AreaShop#344]
#### Current behavior
so im trying to make a player shop, ive made a shop and the player cant access his chest nor place them down. my spawn is priority 1 and my shop is 10.

#### New behavior
idk

#### Steps to reproduce (for bugs)

1. just set up a shop
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 2.4.0
* WorldEdit version: 6.2
* WorldGuard version: 6.1.7.2
* Vault version: 1.5.6
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1201983/AreaShop.zip)
[regions.zip](https://github.com/NLthijs48/AreaShop/files/1201984/regions.zip)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1201982/AreaShop.zip)

**Comment by NLthijs48** [comment]
Your WorldGuard regions look good. Maybe you have not set `spawn-protection` in `server.properties` to `0`? Your spawn region has `block-break: allow` so if people can still not break block at spawn the spawn protection might still be active. Do you get a message from WorldGuard if the player tries to place a block or access the chest?

If spawn protection was not it, you could try the following as `flagProfile` in `default.yml`:

```yaml
  flagProfile:
    ALL: # Flags that should always be applied
      priority: 10
      members: ''
      interact: 'deny g:non_members' # Only allow region members/owners to use things in the region (chests, furnace, animals, etc.)
      use: 'deny g:non_members'
      build: 'deny g:non_members'
      block-break: 'deny g:non_members'
      block-place: 'deny g:non_members'
      chest-access: 'deny g:non_members'
```
