### ISSUE TITLE
flags not working as intended

### ISSUE THREAD

**Issue by Wqrld** [NLthijs48/AreaShop#379]
#### Current behavior
flags dont work how they should

#### New behavior
flags should work by default and flags like pvp defaults should be configurable

#### Steps to reproduce (for bugs)
1. add flags into the config
2. find out they dont work because defaults override it?

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.):  spigot 
* Server version:  1.8.8 R0.1
* AreaShop version:  2.4.0
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1
* Vault version: 1.5.9

#### Your config files (for bugs)

`non-members doesnt seem to be work and have weird overrides`
```
flagProfile:
    ALL: # Flags that should always be applied
      priority: 10
      members: ''
      interact: 'deny g:non_members' # Only allow region members/owners to use things in the region (chests, furnace, animals, etc.)
      build: 'deny g:all'
      chest-access: 'deny g:non_members'
    forrent:
      greeting: ''
      #'%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: ''
      #'%lang:prefix%%lang:greeting-rented%'
    forsale:
      greeting: ''
      #'%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: ''
      #'%lang:prefix%%lang:greeting-bought%'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: ''
      #'%lang:prefix%%lang:greeting-resale%'
```

![2018-01-06_10 11 31](https://user-images.githubusercontent.com/13834197/34638354-0639c0b8-f2ca-11e7-9223-5f4306dafb71.png)
but people cant pvp in regions and members cant interact with stuff
