### ISSUE TITLE
Critical error in permissions

### ISSUE THREAD

**Issue by Roper89** [NLthijs48/AreaShop#427]
1) 
when using "**areashop.landlord.***" permissions, do not work: **areashop.destroyrent.landlord** and **areashop.destroybuy.landlord** (registration for rent and buy works)
Players can  delete "rent" only from the operator's rights (**areashop.destroyrent**).

2)
If i use the permission "areashop.landlord. *" Then when the command "/ as help" is used, I do not see two commands in the prompts: "**/as add**" and "**/as del**"

_(AreaShop 2.4.0, Minecraft ver. 1.12.2)_

**Comment by Roper89** [comment]
@NLthijs48  
I do not understand why permissions do not work. I can not turn off the teleporter. 
My "permissions.yml" (on disable teleport)
```
groups:
  default:
    options:
      default: true
    permissions:
    - areashop.teleportavailable
    - areashop.teleport
    - areashop.find
    - modifyworld.*
schema-version: 1
users: {}

```

My file "permissions.yml" — [drive.google.com](https://drive.google.com/open?id=1mookISqNzqcbbrE9eTy0DkU9tMelRC-1)  
Other permissions work, example: when using **areashop.landlord.***   **work:** areashop.createrent.owner, areashop.createbuy.owner, areashop.setprice.landlord, areashop.setduration.landlord and **do not work:** **areashop.destroyrent.landlord**, **areashop.destroybuy.landlord** 

I used a clean server with different builds of versions 1.12.2
I used different versions: WorldGuard, WorldEdit, Vault, economy (Essentials, Gringotts)
**PermissionsEx-1.23.4**

Help configure permissions. I can give access to the control panel of the server.
