### ISSUE TITLE
Automatic deletion of leases when deleting the WorldGuard region

### ISSUE THREAD

**Issue by Roper89** [NLthijs48/AreaShop#428]
Automatic deletion of leases when deleting the WorldGuard region.

There is a vulnerability when a player deletes his region, but the money for rent is not returned for the paid one.

**Comment by NLthijs48** [comment]
So if I understand correctly, you are allowing players to create WorldGuard regions, add them to AreaShop and then make money by selling/renting them to others? And because they can also remove these WorldGuard regions the issue you describe can happen.

I assume players can only remove WorldGuard regions that they are the owner of right? If that is the case you could configure AreaShop to remove the landlord from the WorldGuard region when a player buys/rents the region, and add the landlord back when the rent is over. That way they should only be able to remove the region when it is not rented/bought by anyone.

Would that solution work for you and do you need any help setting it up?

PS: nice Red Alert 2 profile picture ;)

**Comment by Roper89** [comment]
I liked your suggestion. How to configure the plugin to work this way?

P.S. Thank :) I play a modification of Red Alert 2 on the network.

Video Red Alert 2: REBORN (MOD):
https://www.youtube.com/watch?v=0s7HXEhqXmI
https://www.youtube.com/watch?v=y9DcY1UedU8&t

Download: https://www.dropbox.com/s/08bzovehxrjt9rq/Reborn.zip

**Comment by NLthijs48** [comment]
How are the landlords currently added to WorldGuard regions? I assume in the 'owners' list? And the renter of the region is added in the 'members' list?

You could change the `flagProfile` section in `default.yml` to the following to do the setup:
```yaml
  flagProfile:
    ALL: # Flags that should always be applied
      priority: 10
      owners: ''
      members: ''
      interact: 'deny g:non_members' # Only allow region members/owners to use things in the region (chests, furnace, animals, etc.)
      use: 'deny g:non_members'
      build: 'deny g:non_members'
      block-break: 'deny g:non_members'
      block-place: 'deny g:non_members'
    forrent:
      owners: '%landlorduuid%'
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
    forsale:
      owners: '%landlorduuid%'
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
    resell:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
```

Note that only in the `forrent` and `forsale` states of the region the `%landlorduuid%` is added as an owner, and in the other states the owner is removed because of the rule in `ALL`.

Let me know if that works!

Cool that there is such a modded version of Red Alert 2, I did not know something like that existed. I recently did the whole campaign again of the original game :)
