### ISSUE TITLE
Enhancement: Add actions confirmations

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#50]
I would like to see that actions with commands like `as buy` as well as using the sign would need a confirmation like `If you are sure please retype the command` or `/as yes`.

The story behind is, that I am pretty sure that players will complain when they "accidently" hit the sign to unrent their shop or whatever and with schematics enabled all their stuff will be deleted.

**Comment by NLthijs48** [comment]
I agree this would be a good thing to add, this feature was actually on my old TODO list (google drive file), apparently I forgot to move it to a feature issue here on GitHub.

If you want to have a confirmation step with the current version of AreaShop you can change the 'signProfiles' to use a tellraw command instead of the AreaShop command for buying/selling. Then this tellraw command asks if the users really wants to do it, and has parts you can click to accept the action (which performs the actual AreaShop command).

An example would be like this:
```
/tellraw @p ["",{"text":"[Areashop]","color":"dark_green"},{"text":" Are you sure you want to sell your region? ","color":"white"},{"text":"[Yes, go ahead]","color":"dark_green","clickEvent":{"action":"run_command","value":"/areashop sell %region%"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click to sell your region"}]}}}]
```
I created this command with a [Tellraw Generator](http://www.minecraftjson.com/), which makes it quite easy to do things like this.

**Comment by EvilOlaf** [comment]
Nice.  Will give it a try.
I do not use AreaShop in production yet, just on the dev server ;).

**Comment by NLthijs48** [comment]
Okey, let me know if you have any other questions :smile:

**Comment by EvilOlaf** [comment]
Sure thing :P

**Comment by EvilOlaf** [comment]
The suggested tellraw command works well.
This would probably allow me to run AreaShop without needing any commands at player side. Kind a comfortable :P

**Comment by EvilOlaf** [comment]
I should have tried these without op...
`rightClickPlayer` give me an error as expected as players do not have permissions for tellraw.
Debug output was `[17:58:39 INFO]: [AreaShop] Debug: Command run, executor=Olaf, command=tellraw ..... result=true`
`rightClickConsole` ignoring the whole tellraw thing and does the default action instead like rent or unrent. 

This was with `rightClickConsole` and `shiftRightClickConsole`
```
[17:59:39 INFO]: [AreaShop] Debug: Performing periodic sign update...
[17:59:41 INFO]: [AreaShop] Debug: Olaf has rented region shop1 for 803 USD until 12.09.2015 17:59
[17:59:41 INFO]: [AreaShop] Debug: Command run, executor=Olaf, command=areashop rent shop1, result=true
[17:59:42 INFO]: [AreaShop] Debug: Olaf has unrented shop1, got 1605.97 NAC money back
[17:59:42 INFO]: [AreaShop] Debug: Schematic operations for shop1 not enabled, skipped
[17:59:42 INFO]: [AreaShop] Debug: Command run, executor=Olaf, command=areashop unrent shop1, result=true
```

**Comment by NLthijs48** [comment]
You should indeed use the console versions, if the default action is ran instead then you have your profile incorrect (leave the default sections there, but remove the commands, or create a profile with different name).

One thing that might be the problem is that you should not use `@p`, since Bukkit/Spigot does not support those, simply use `%player%` instead. I'll change that in my earlier message because otherwise this might be confusing.

**Comment by EvilOlaf** [comment]
Hey, 
thanks for the quick response. I'll give it a try.

**Comment by EvilOlaf** [comment]
Either I'm doing it wrong or there is an issue with this.
`config.yml`
http://pastebin.com/LeA1is2K

`default.yml` not been changed and copied to `default2.yml` for testing.

**Comment by NLthijs48** [comment]
I tried it myself, first of all your command lines are not indented correctly (the `-` should be at the same indentation). And the other incorrect thing is `%player%`, since the region is not yet rented/bought the variable `%clicker%` should be used, which holds the name of the player that clicks the sign (my fault for giving your the incorrect variable).

This is the profile I have tried:
```yaml
  confirm:
   ## The following sections can be added for performing certain commands when the sign is clicked:
    ## rightClickPlayer, rightClickConsole, shiftRightClickPlayer, shiftRightClickConsole,
    ## leftClickPlayer, leftClickConsole, shiftLeftClickPlayer, shiftLeftClickConsole.
    ## Sections with 'Player' at the end will be run by the clicking player and 'Console' ones from the console.
    forrent:
      line1: '&2&l[Zur Miete]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickConsole:
      - 'tellraw %clicker% ["",{"text":"[","color":"yellow"},{"text":"Server","color":"aqua"},{"text":"]","color":"yellow"},{"text":" Willst du diesen Shop wirklich mieten? ","color":"green"},{"text":"[Ja (klick mich)]","color":"dark_green","clickEvent":{"action":"run_command","value":"/areashop rent %region%"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Klick mich um diesen Shop zu mieten"}]}}}]'
      leftClickPlayer:
      - 'areashop info region %region%'
    rented:
      line1: '&4&l[Vermietet]'
      line2: '%region%'
      line3: '%player%'
      line4: '%untilshort%'
      rightClickPlayer:
      - 'areashop rent %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickConsole:
      - 'tellraw %clicker% ["",{"text":"[","color":"yellow"},{"text":"Server","color":"aqua"},{"text":"]","color":"yellow"},{"text":" Willst du diesen Shop wirklich kündigen? ","color":"green"},{"text":"[Ja (klick mich)]","color":"dark_green","clickEvent":{"action":"run_command","value":"/areashop unrent %region%"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Klick mich um diesen Shop zu kündigen"}]}}}]'
    forsale:
      line1: '&2&l[Zum Verkauf]'
      line2: '%region%'
      line3: '%price%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
    resell:
      line1: '&9&l[Wiederverkauf]'
      line2: '%region%'
      line3: '%resellprice%'
      line4: '&8%player%'
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop stopresell %region%'
    sold:
      line1: '&4&l[Verkauft]'
      line2: '%region%'
      line3: '%player%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop sell %region%'
```
Also make sure that the correct signProfile is applied to the region by setting `signProfile` in `default.yml` to the correct one.
