### ISSUE TITLE
I would like to be able to use multiple flag profiles.

### ISSUE THREAD

**Issue by PieCrafted** [NLthijs48/AreaShop#532]
**Describe the problem you are trying to solve with this feature request**

I am running a prison server. There is a certain group of cells that I want players to NOT be able to break/place blocks in the region. All other groups of cells they should be allowed to build/break whatever they want.

The default flag profile works perfectly for my second sentence up above. However, when I try to add a custom flag profile to the group described in my first sentence using [the instructions in this link](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#why-is-my-custom-profile-not-working-flagprofile-signprofile-etc), all the flags for all the regions in the server revert to the default flags and if a player rents any region they won't be added as a member in the WorldGuard flags.

This is what I am typing into my groups.yml

```
cblock-cells:
  name: cblock-cells
  priority: 0
  rent:
    price: 100
    duration: 1 day
  general:
    flagProfile:
      ALL:
        block-break: 'deny'
        block-place: 'deny'
  regions:
  - REGION-XYZ
```

If I am supposed to modify defaults.yml, please post an example of what I should do because there is no wiki page on having multiple flag profiles.

Thank you!

**Describe the solution you'd like**
To be able to do what I am describing above.
