### ISSUE TITLE
Limits based on groups not working

### ISSUE THREAD

**Issue by TomLewis** [NLthijs48/AreaShop#551]
I have multiple groups of shops for rent around my single world, All I want to do is limit (for everyone) so that they can only rent 1 shop each, but rent docks at the same time.

Why is this not working?

config
```
limitGroups:
  survivalshops:
    total: 1
    rents: 1
    buys: 0
    groups:
    - 'shops'
  survivaldocks:
    total: 5
    rents: 5
    buys: 0
    groups:
    - 'docks'
  survivalstalls:
    total: 1
    rents: 1
    buys: 0
    groups:
    - 'stalls'
```

Permissions
```

- areashop.limits.survivalshops:
    world: PirateCraft_1
    value: true
- areashop.limits.survivaldocks:
    world: PirateCraft_1
    value: true
- areashop.limits.survivalstalls:
    world: PirateCraft_1
    value: true
```
