### ISSUE TITLE
eventCommandProfiles per group?

### ISSUE THREAD

**Issue by TomLewis** [NLthijs48/AreaShop#568]
**Current behavior**
eventCommandProfiles is global to all groups, can I specify eventCommandProfiles for all groups apart from one?

**Desired behavior**
I figured out DiscordSRV allows sending messages to channels, so I wanted to alert each time a shop was bought/sold, which works! `discord broadcast` easy, but what I didnt consider is there is 1 group of shops I don't want to be broadcast as its spammy with how often they are rented/unrented. 

Is there a way to set `eventCommandProfiles` events before/after to only happen on a whitelist of groups, I only want to run the `discord broadcast` on 3 groups when they are unrented/rented and ignore 1 group set. So it could be a blacklist.

```
    unrented:
      before:
      after:
      - "say Shop %region% was un-rented and is now available."
      - "discord broadcast #theidhere :coin: **%region% was un-rented and is now available.**" <-somehow block this being sent for 1 group.
```

Another question, in the parameters we have %region%, is there one for the %username% of the person that rented it? and also one for the time/date it happened?

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: Paper 1.12.2
* AreaShop version: 2.6.0
* WorldEdit version: 6.1.7
* WorldGuard version: 6.2.2
* Vault version: 1.6.6
