### ISSUE TITLE
help with greetings

### ISSUE THREAD

**Issue by Nacholebraa** [NLthijs48/AreaShop#590]
**Current behavior**
When I buy and sell a region the greetings of the world guard region don't disable. 

**Desired behavior**
Wondering how to disable the greetings for everything, but keep the greetings for when a property is for sale,rent, resell

**Your environment**
1.116.5

* Server platform (Bukkit, Spigot, etc.): 
* Server version:  This server is running Paper version git-Paper-782 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 3 version(s) behind
* AreaShop version:  2.6.0
* WorldEdit version: 7.2.5+57d5ac9
* WorldGuard version: 7.0.5+3827266
* Vault version: 1.7.3-b131

**Your config files**
[AreaShop and WorldGuard.zip](https://github.com/NLthijs48/AreaShop/files/6950172/AreaShop.and.WorldGuard.zip)

**Comment by iiMilan** [comment]
I found this in the config. Maybe you could tune some of those settings.

```yaml
  ##### Set WorldGuard regions flags depending on the region state.
  # All normal region flags as present in WorldGuard can be used, in addition to 'members', 'owners', 'priority' and 'parent'.
  # The members and owners flag normally take a list of UUID's separated by a comma, adding by name is possible with 'n:<name>'.
  # You can add groups by using 'g:<groupname>', so an example woul be: '%uuid%, %friendsuuid%, g:vip, n:coolGuy'.
  # For allow/deny flags like 'entry' and 'exit' you can set the group setting by using 'g:<scope>', <scope> is one of the following:
  #     members, non_members, owners, non_owners, all. Example, only members can enter the region:
  #       entry: 'deny g:non_members'
  # '' will remove the flag from the region.
  flagProfile:
    ALL: # Flags that should always be applied
      priority: 10
      owners: ''
      members: ''
      interact: 'deny g:non_members' # Only allow region members/owners to use things in the region (chests, furnace, animals, etc.)
      use: 'deny g:non_members'
      build: 'deny g:non_members'
      block-break: 'deny g:non_members'
      block-place: 'deny g:non_members'
    forrent:
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: ''
      greeting: ''
    forsale:
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: ''
      greeting: ''
    resell:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
```
