### ISSUE TITLE
changing the name

### ISSUE THREAD

**Issue by hyrixx** [NLthijs48/AreaShop#594]
hi
i want when player buy a shop region
the shop region name change to the player name

**Comment by iiMilan** [comment]
I found this in the default.yml files:
Maybe you can change some things of this to get your thing you needed.

```yaml
  ##### Run commands when an event happens.
  # Commands at a 'before' section will execute before the region details are changed in the AreaShop system
  # and before any other actions occurred (setting the owner, saving/loading schematics, etc.),
  # the 'after' commands will be run when all changes are done.
  # You can add a list of commands to 'before' and 'after'.
  eventCommandProfile:
    created:
      before:
      after:
    #  - "say An AreaShop region has been created: %region%"
    deleted:
      before:
      after:
    rented:
      before:
      after:
    extended:
      before:
      after:
    unrented:
      before:
      after:
    bought:
      before:
      after:
    sold:
      before:
      after:
    resell:
      before:
      after:
```
