### ISSUE TITLE
Hi, how can i make so only a group can buy a serten group of cells

### ISSUE THREAD

**Issue by Zakota3223** [NLthijs48/AreaShop#597]
**Current behavior**
how can i make so only a group can buy a serten group of cells

**Desired behavior**
i want so only people with rank "Snowmand" or has a permission to be able to buy/rent it, and noone else

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version:  1.8.9
* AreaShop version:  2.6.0
* WorldEdit version:  6.1.7;dd00bb1
* WorldGuard version:  6.1.3-SNAPSHOT;c904242
* Vault version: 1.7.3-SNAPSHOT;c904242

**Your config files**
Dont rly think this matters here

**Comment by iiMilan** [comment]
You can set a limit in the config files if that is what you are looking for.

See these 2 perms for a bit of help:
- `areashop.limits.default (true)` - Gives you the group 'default' as limits for number of rent/buy/total regions
- `areashop.limits.` - Gives you the group with that name with the limits as specified in the config in the 'limitGroups' section 

**You can use this for example in your config.yml:**
```yaml
limitGroups:
  default:
    total: 0
    rents: 0
    buys: 0
  snowmand: #permissions node areashop.limits.snowmand
    total: 1
    rents: 1
    buys: 1
```
