### ISSUE TITLE
Sign disappearing after unrent, as reload fixes that.

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#65]
As the topic says since the daily restart this morning I have a weird issue that lets as signs disappear after unrenting a region.
A `/as reload` fixes this and the signs re-appearing. Debug mode is enabled and I waited if a periodic sign update fixes it but it doesn't.
Unfortunately AreaShop does not provide any further debug information.

`config.yml` http://pastebin.com/88KMAHXj
`default.yml` http://pastebin.com/Q8cKA3zX
These pastes will expire in one month from now.

The only thing I changed till then was adding `chest-access` to the flags section. I removed this again for testing purpose but did not change the behavior.

v2.2.0

**Comment by NLthijs48** [comment]
Signs will only disappear if all the lines `line[1-4]` are empty in the signProfile of the sign. So it might be that the assigned signProfile is missing/broken, therefore removing the signs. Check the `<region>.yml` file to see if the sign with trouble has a signprofile, then check for a general signprofile in the `<region.yml>`, then for groups assigned to the region, and lastly the default file.

The periodic sign update task will not do anything about this problem, that will only update signs that have the `%timeleft%` tag on them (only time-sensitive tag). So you don't have to check on that.

Since you are describing that `/as reload` fixes the problem I don't really get where the problem is coming from. If you can describe a way to reproduce this problem then I might try it myself with your config, maybe I can spot the problem then.

**Comment by EvilOlaf** [comment]
SignProfiles are correct. Otherwise they won't work (again) on (re)load.
I checked all `region` files and the only difference between is that one contains `lastActive:` and `Duration:` line. This particular one I used for testing. I set the duration from default 7 days to 2 days (german `Tage` which is added to the bunch of terms at the `config.yml`). That part works well.

```
$:~/plugins/AreaShop/regions$ cat shop1.yml
general:
  name: shop1
  world: Survival
  type: rent
  signs:
    '0':
      location:
        world: Survival
        x: 3150.0
        y: 74.0
        z: 1535.0
      facing: SOUTH
      signType: WALL_SIGN
  lastActive: 1441290747155
rent:
  price: 1606.0
  duration: 2 Tage
```


```
$:~/plugins/AreaShop/regions$ cat shop2.yml
general:
  name: shop2
  world: Survival
  type: rent
  signs:
    '1':
      location:
        world: Survival
        x: 3159.0
        y: 74.0
        z: 1534.0
      facing: WEST
      signType: WALL_SIGN
rent:
  price: 2486.0
```
All other regions look like `shop2` as they have not been used yet.
