### ISSUE TITLE
How do I specify region groups to get different flags?

### ISSUE THREAD

**Issue by c0wg0d** [NLthijs48/AreaShop#67]
Let's say I have group1 and group2.  How can I setup a different flagProfiles for each group?  I want to deny building for group1 shops but allow owners to build their own shops in group2.  Would it look like this?
<pre>
flagProfiles:
  default:
    forrent:
      members: ''
      build: 'deny'
      groups:
      - group1
      - group2
    rented:
      members: '%uuid%, %friendsuuid%'
      build: 'deny'
      groups:
      - group1
    rented:
      members: '%uuid%, %friendsuuid%'
      build: 'allow'
      groups:
      - group2
</pre>

**Comment by NLthijs48** [comment]
To get different flags for different groups you can first create 2 flagProfiles. To do that you have to copy everything from the `default` profile and paste it below it again, and then change the name to something else (so change `default:` to `group2:` or something like that). So you would get something like this:
```yaml
flagProfiles:
  default:
    forrent:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
    forsale:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
  group1:
    forrent:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
    forsale:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
  group2:
    forrent:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-rented%'
    forsale:
      members: ''
      greeting: '%lang:prefix%%lang:greeting-forsale%'
    sold:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-bought%'
    resale:
      members: '%uuid%, %friendsuuid%'
      greeting: '%lang:prefix%%lang:greeting-resale%'
```

Then you can change the flags of both groups as you like (change the greeting messages, add flags, etc.). To assign the correct profile to the correct group you can use the `groups.yml` file. I'm assuming you have already added all regions to a group using `/as groupadd`. Open `groups.yml` and add the `flagProfile` setting inside a `general` section inside a group. Set this setting to a string with the name of the flagProfile. This would result in something like this:
```yaml
group1:
  name: Group1
  priority: 0
  general:
    flagProfile: "group1"
  regions:
  - house_1
  - house_2
  - house_3
group2:
  name: Group2
  priority: 0
  general:
    flagProfile: "group2"
  regions:
  - plot_1
  - plot_2
  - plot_3
```

One reason why your tried solution does not work is the fact that YAML files do not accept 2 keys with the same name as child of the same parent (so the 2 `rented` sections you have cannot be read both, only the bottom one will go through to AreaShop).

Let me know if you managed to get it working with my above explanation or if you need more help.
