### ISSUE TITLE
Change player's permissions when he buys region

### ISSUE THREAD

**Issue by TweetsOfNiklas** [NLthijs48/AreaShop#97]
Hello,

I would like to add a few lines of code in AreaShop, because I would like to add Players, who buy a region, to another group in PermissionsEx. e.g. from *'Guest'* to *'Resident'*. With this change he would also get more permissions on the server.

So the question is: Where is the best location to add these lines? Because the player should only get the permissions if he really bought the region, and not when he has e.g. not enough money.

Thanks

**Comment by NLthijs48** [comment]
I don't think you need to change to code of AreaShop in this case to get what you want. You can simply add a command to the `eventCommandProfiles` section in the `config.yml` file.

If you also need to remove the player from the PermissionsEx group when he stops renting a region then it wil get harder. It will work correctly when a player can only have 1 region at a time, but if you allow them to have more then the `eventCommandProfiles` thing is not enough anymore. Because if a player has 2 regions and unrents/sells one then he would get removed, while in fact he still has one region.

Let me know if the `eventCommandProfiles` section is enough for you or if you do need to change something in the code. In this case it might also be better write a plugin that hooks into AreaShop instead of changing AreaShop itself, because then you can still easily update AreaShop.

**Comment by TweetsOfNiklas** [comment]
Ok, thank you. Players on our server can only buy regions, so it's not the problem. The problem is, when a player has the permission group 'VIP' for example, he always gets downgraded to Resident.

I edited the config now to:
```
    bought:
      before:
      after:
  ##  - "pex user %player% group set Resident *
```

Or should I do this:
```
    bought:
      before:
      after:
  ##  - "pex user %player% group add Resident *
  ##  - "pex user %player% group remove Resident *
```
Would it prevent my problem, when I only add/remove groups to the existing?
